config/routes.rb
Rails.application.routes.draw do
  root 'photos#list'

  get 'photos/new' => 'photos#new', as: :new_photo
  get 'photos/:id' => 'photos#detail', as: :photo
  post 'photos' => 'photos#create', as: :photos
  post 'photos/:id/like' => 'photos#like', as: :like_photo

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  # validates :url, presence: true

  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def list
    @photos = Photo.all
                   .order("view_count desc")
                   .page(params[:page])
                   .per(4)
  end

  def detail
    @photo = Photo.find params[:id]
  end

  def like
    @photo = Photo.find params[:id]
    @photo.update view_count: (@photo.view_count + 1)
    redirect_to root_path
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new params.require(:photo).permit(:image)
    if @photo.save
      redirect_to photo_path(id: @photo.id)
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photolog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <h1><%= link_to 'Photos', root_path %></h1>
  <%= yield %>
</div>

</body>
</html>

app/views/photos/detail.html.erb
<h1><%= pluralize @photo.view_count, 'like' %></h1>


<%= image_tag attachment_url(@photo, :image, :fit, 500, 500, format: "jpg") %>

app/views/photos/list.html.erb
<div class="well">
  <div class="text-right">
    <%= link_to 'New Photo', new_photo_path, class: 'btn btn-default' %>
  </div>
</div>

<div class="text-center">
  <%= paginate @photos %>
  <p>
    <%= page_entries_info @photos %>
  </p>
</div>



<% @photos.each do |photo| %>

  <div class="col-xs-6">
    <%= link_to photo_path(id: photo.id) do %>
      <%= image_tag attachment_url(photo, :image, :fill, 400, 400, format: "jpg") %>
      <% end %>

    <%= link_to like_photo_path(id: photo.id), method: :post, class: 'btn btn-default'  do %>
      <i class="glyphicon glyphicon-thumbs-up"></i>
      <%= pluralize photo.view_count, 'like' %>
    <% end %>


  </div>

<% end %>

app/views/photos/new.html.erb
<h1>New Photo!</h1>

<%= form_for @photo do |f| %>

  <div class="form-group <%= 'has-error' if @photo.errors[:image].any? %>">
    <%= f.label :image, class: 'control-label' %>
    <%= f.file_field :image %>
    <p class="help-block"><%= @photo.errors[:image].join(", ") %></p>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary btn-lg' %>
  </div>

<% end %>